### ISSUE TITLE
stack level too deep when running precompile (3.1.6)

### ISSUE THREAD

**Issue by developers-kentaa** [rails/sass-rails#100]
once upgraded from sass-rails 3.1.5 to 3.1.6 I get an stack level to deep when running bundle exec rake RAILS_ENV=staging RAILS_GROUPS=assets assets:precompile

Works fine using 3.1.5, crashes when using 3.1.6

css file mentioned in the stack trace (fonts.css.scss)

``` css
@font-face {
    font-family: 'ITCAvantGardeGothicStdMedium';
    src: url('/fonts/itcavantgardestd-md-webfont.eot');
    src: url('/fonts/itcavantgardestd-md-webfont.eot?#iefix') format('embedded-opentype'),
         url('/fonts/itcavantgardestd-md-webfont.woff') format('woff'),
         url('/fonts/itcavantgardestd-md-webfont.ttf') format('truetype'),
         url('/fonts/itcavantgardestd-md-webfont.svg#ITCAvantGardeGothicStdMedium') format('svg');
    font-weight: normal;
    font-style: normal;

}

.avantgarde-medium {
    font-family: 'ITCAvantGardeGothicStdMedium';
    font-weight: normal;
}
```
