### ISSUE TITLE
Filenames in asset helpers require quotes

### ISSUE THREAD

**Issue by pixeltrix** [rails/sass-rails#12]
Is there any reason why the following couldn't be made to work:

``` scss
#logo { background-image: image_url(logo.png); }
```

Currently you have to enclose the path in quotes - unless there's no file extension, e.g:

``` scss
#logo { background-image: image_url('logo.png'); }
#logo { background-image: image_url(logo); }
```

Since url() doesn't use quotes it means that when converting a CSS file to SCSS you have to wrap all the paths if you want to use the asset helpers.
