### ISSUE TITLE
Compression doesn’t work in Rails 4

### ISSUE THREAD

**Issue by ai** [rails/sass-rails#135]
I use Rails from git, sprockets-rails 2.0.0.rc2, sprockets 2.8.2 and sass-rails from Git.

But, when assets compiled, CSS was uncompressed, like:

``` css
/*
 * Fotorama 4.0 | MIT License
 */
.fotorama__stage__shaft, .fotorama__stage__frame {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  right: 0;
  left: 0;
  bottom: 0; }
```

JS compressor (Uglifier) work fine.
