### ISSUE TITLE
file.css(.scss).erb causes `File to import not found or unreadable`

### ISSUE THREAD

**Issue by JeanMertz** [rails/sass-rails#139]
Using the ERB handler breaks reading/importing the files…

This works:

``` scss
// application.css.scss:
@import 'tester'

// tester.css(.scss)
body { color: #ABC; }
```

This does not:

``` scss
// application.css.scss:
@import 'tester'

// tester.css(.scss).erb
body { color: #ABC; }
```

**Sass::SyntaxError: File to import not found or unreadable**

At first I thought it was related to #119 or #94, but those fixes don't solve my problem. I do use `Rails 4.0.0.beta1` (together with `sass-rails 4.0.0.beta1`), so perhaps this could be related?
