### ISSUE TITLE
Can we reference the /assets path even when asset_host is set?

### ISSUE THREAD

**Issue by zilkey** [rails/sass-rails#171]
We have an issue with our CDN where it can't serve our icon font files correctly.  We'd like to be able to use `asset-url` for all of our images, but reference `/assets` for our font files.

So for example:

``` css
p { 
  background: asset-url('foo.png') // => http://ourcdn.com/foo-9c8c96c7f995b38e932e0f3e.png
}  

p { 
  font-family:'our-icons';
  src:hostless-asset-url(/assets/our-icons.eot) // => /assets/our-icons-987654ewsdfyui8765e.eot
}  
```

Is this possible out-of-the-box?

I contribute to a gem that provided this functionality for rails 3 ( https://github.com/doorsteps/hostless-sass-assets ) but it breaks when used with Sass-Rails 4.  We're planning to add Rails 4 support soon, but I wanted to see if this was supported before we made the effort.

In Sass-Rails 3, there was a method named `public_path` in Sass::Rails::Helpers (https://github.com/rails/sass-rails/blob/master/lib/sass/rails/helpers.rb - https://github.com/rails/sass-rails/commit/6dbe00ef95fa766a02813bb126b8531582e24882) but that's gone now.

Thanks,

Jeff
