### ISSUE TITLE
new files added that match a glob are not detected automatically in development

### ISSUE THREAD

**Issue by aaronjensen** [rails/sass-rails#189]
You have to make a change to the file that includes the glob statement. For example:

`foo.sass`:

```sass
@import foo/*
```

with `foo/bar.sass`:

```sass
body
  color: red
```

Load the css in the browser. Then add:

`foo/bar2.sass`:

```sass
body
  background: blue
```

And refresh the css. I expect to see the new rule, but instead I have to go add a new line or something to `foo.sass`

**Comment by bolandrm** [comment]
I just tried to reproduce this and I could not.  I did the following:

- new rails app;
- sass rails 5.0.4
- no spring

```scss
// application.scss

@import "globbed/*";
```
```scss
// globbed/test1.scss

body { background-color: red; }
```

Loaded page.

Added:
```scss
// globbed/test2.scss

body { font-size: 50px; }
```

Refreshed; saw changes.

Is anyone able create an app that reproduces this?
