### ISSUE TITLE
image-url not adding digest on staging environment.

### ISSUE THREAD

**Issue by BilalBudhani** [rails/sass-rails#256]
When I run `assets:precompile` for staging environment it does not add digest to assets. However, It works fine for production. 

This is a gist of my scss code:

``` css
.hero-unit {
  background: image-url('slide-living-room.jpg');
  background-size: cover;
  height: 50rem;
}
```

output:

``` css
.hero-unit{background:url(/assets/slide-living-room.jpg);background-size:cover;height:50rem}
```

As you can see it is not adding digest to the generated links. I've attached more technical details of my project below.

config/environments/staging.rb

``` ruby
config.assets.css_compressor = :sass
config.assets.digest = true
```

Gemfile

``` ruby
gem 'rails', '4.1.6'
gem 'sass-rails', '~> 4.0.3'
```

Ruby: 2.1.2
Rails: 4.1.6

What could possibly wrong in the setup?
