### ISSUE TITLE
Inconsistence of &

### ISSUE THREAD

**Issue by SebastianOsuna** [rails/sass-rails#311]
According to lo sass-lang.com/documentation I can do the two following things:
```CSS
.foo.bar .baz.bang, .bip.qux {
  $selector: &;
}
```
```CSS
#main {
  color: black;
  &-sidebar { border: 1px solid; }
}
```

But while using 5.0.1 I get

`Invalid CSS after "  $selector: ": expected expression (e.g. 1px, bold), was "&;"`
And
`Invalid CSS after "  &": expected "{", was "-sidebar {"`
