### ISSUE TITLE
*-path helpers include host when config.asset.host set

### ISSUE THREAD

**Issue by bschaeffer** [rails/sass-rails#355]
When `config.asset.host` is set, it is included in the output `*-path` helpers. I'm not sure if this is expected behavior, but it seems like it shouldn't be because we have both `*-path` and `*-url` helpers. Anyway, take the following.

**application.css.scss**

```css
div {
  background: url(image-path('awesome/image.png'));
}
```

**development.rb**:

```ruby
config.asset.host = nil
```

...and then `rake assets:precompile` produces:

```css
div {
  background: url('/assets/awesome/image.png');
}
```

**production.rb**

```ruby
config.asset.host = "https://mycdn.com/"
```

...and then `RAILS_ENV=production rake assets:precompile` produces:

```css
div {
  background: url('https://mycdn.com/assets/awesome/image-{fingerprint}.png');
}
```

Is this the desired output? Not sure how to get the compiler to respect the fact that I want the path only.
