### ISSUE TITLE
@font face does not seems to work

### ISSUE THREAD

**Issue by softmonkeyjapan** [rails/sass-rails#371]
I'm trying (again) to include some custom fonts within the assets pipeline and to tell you the truth this is always a nightmare.

Basically, I'm running a brand new Rails app (4.2.0) and I added my fonts at `app/assets/fonts`. I also register a new asset path within my `initializers/assets.rb`: 

```ruby
Rails.application.config.assets.paths << Rails.root.join('app', 'assets', 'fonts')
Rails.application.config.assets.precompile += %w( .svg .eot .woff .ttf )
```

Then, as we can read everywhere, we need to use `font-url` (`font-path`) or `asset-path`, which I did : 

```css
@font-face {
	font-family: 'UXPin-icon-set';
	src: url(font-path('UXPin-icon-set.eot?kib1r2'));
	src: url(font-path('UXPin-icon-set.eot?#iefixkib1r2')) format('embedded-opentype'),
		   url(font-path('UXPin-icon-set.woff?kib1r2')) format('woff'),
		   url(font-path('UXPin-icon-set.ttf?kib1r2')) format('truetype'),
		   url(font-path('UXPin-icon-set.svg?kib1r2#UXPin-icon-set')) format('svg');
	font-weight: normal;
	font-style: normal;
}
```

and of course this isn't working. I've try replacing `font-url` with `asset-path` and I even try everything describe here [https://gist.github.com/anotheruiguy/7379570](https://gist.github.com/anotheruiguy/7379570) but nothing works.

I'm pretty sure I'm doing something wrong somehow but honestly, the only thing in Rails that never works out of the box is this case, the fonts, or maybe there is somehow a lack in the documentation not explaining very well how to do it (searching on google will show thousand of cases like this one, so I'm not the only one, people are having trouble with this).

Sorry for the complaining, just wanted to pointed out this. Thanks for your great work and future answer.
