### ISSUE TITLE
Scss suffixes is not working

### ISSUE THREAD

**Issue by ruannawe** [rails/sass-rails#450]
When I run the command: `bundle exec rake assets:precompile`.

I receive the following error: `Sass::SyntaxError: Invalid CSS after "&-": expected number or function, was "-another {"`.

My code:
```scss
.example {
    &-another {
        color: red;
    }
}
```

I'm using version 6 when I receive this error. Version 5.1 compile WITHOUT errors. Probably some bug between these two versions.
