### ISSUE TITLE
Assets paths for SASS-files

### ISSUE THREAD

**Issue by fxposter** [rails/sass-rails#7]
If I have a SASS partial, which uses some context (sass-variables, mixins, extends other classes), it should be included in main sass file using @import (which prevents me from using Tilt's ability to use ERB), but that causes problems for images: I can't use something like that:

``` css
  body { 
    background: url('background.png');
  }
```

cause on production this image will be precompiled and would have another name (with md5-hash).
